/** M5.b renderer copy. M5.c will select the active locale at runtime. */
export const appLocales = ['zh-CN', 'zh-TW', 'en', 'ja', 'ko'] as const
export type AppLocale = (typeof appLocales)[number]

export const strings = {
  titlebar: {
    newSession: '新建',
    settings: '设置',
    minimize: '最小化',
    maximize: '最大化',
    restore: '还原',
    close: '关闭'
  },
  common: {
    close: '关闭',
    view: '查看',
    cancel: '取消',
    confirm: '确认',
    disabledUntilM5c: 'M5.c 开放',
    justNow: '刚刚',
    minutesAgo: (minutes: number) => `${minutes} 分钟前`,
    hoursAgo: (hours: number) => `${hours} 小时前`,
    daysAgo: (days: number) => `${days} 天前`
  },
  navigation: {
    home: 'Home',
    newSession: 'New Session',
    sessions: 'Session',
    terminals: 'Terminal',
    settings: '设置',
    emptySessions: '暂无会话',
    emptyTerminals: '暂无终端',
    expandSidebar: '展开侧栏',
    collapseSidebar: '收起侧栏',
    closeTerminal: '关闭终端',
    closeSession: '关闭会话'
  },
  sessionStatus: {
    working: '运行中',
    needsYou: '待处理',
    done: '已完成',
    error: '出错',
    idle: '空闲',
    exited: '已退出',
    exitedDetail: (exitCode: number) => `已退出：exit code ${exitCode}`
  },
  home: {
    greetings: [
      { text: 'Hi! Ready to coding?', keywords: ['coding'] },
      { text: 'Welcome back, builder.', keywords: ['builder'] },
      { text: 'Let’s ship something today.', keywords: ['ship'] },
      { text: 'Your agents are standing by.', keywords: ['agents'] },
      { text: 'Coffee first, then commits.', keywords: ['commits'] },
      { text: 'One more session won’t hurt.', keywords: ['session'] },
      { text: 'Good timing. Let’s vibe.', keywords: ['vibe'] },
      { text: 'Pick a CLI and go.', keywords: ['CLI'] }
    ],
    quickLaunch: '快速启动',
    terminal: '终端',
    freshLabel: 'home · getting started',
    freshTitle: 'Welcome. Pick a CLI and go.',
    freshHint: '还没有会话。选一个入口开始，AI CLI 的状态与提醒会汇聚到这里。',
    freshCollect: '启动后这里会汇聚',
    historyStats: '· 历史事件与 all-time 统计',
    deskLabel: 'home · session desk',
    waitingApproval: (count: number) => `${count} waiting approval`,
    errors: (count: number) => `${count} errors`,
    live: (count: number) => `${count} live`,
    defaultTerminal: (name: string) => `默认：${name}`,
    terminalOptions: '终端选项',
    attention: '注意力优先',
    allStatuses: '全部',
    emptyAttention: '当前没有待处理或出错的会话',
    showMore: '展开更多',
    showLess: '收起',
    showAll: (count: number) => `展开全部 ${count} 条 ↓`,
    recentHistory: '历史事件',
    allTime: '概览',
    stats: {
      sessions: '历史启动',
      tools: 'Tools 调用',
      alerts: '阻塞提醒',
      approvals: '已处理批准'
    }
  },
  settings: {
    title: '设置',
    sections: {
      appearance: '外观',
      layout: '布局',
      terminal: '终端',
      session: '会话'
    },
    uiTheme: '界面主题',
    uiThemeHint: '只影响应用界面，与终端配色相互独立',
    light: '浅色',
    dark: '深色',
    darkDisabledHint: '深色界面主题归 M5.c',
    language: '界面语言',
    languageHint: '五语言 i18n 归 M5.c',
    languages: {
      'zh-CN': '简体中文',
      'zh-TW': '繁體中文',
      en: 'English',
      ja: '日本語',
      ko: '한국어'
    },
    navigationMode: '导航模式',
    navigationModeHint: '三态互斥；顶部 Tab 模式无侧栏',
    sidebar: '侧栏展开',
    rail: '侧栏收起',
    tabs: '顶部 Tab 栏',
    floatingWindow: '悬浮窗',
    floatingWindowHint: '独立置顶小窗，随 S3 落地',
    terminalTheme: '终端配色',
    terminalThemeHint: '16 色方案，独立于界面主题',
    font: '字体',
    fontHint: '内嵌 Maple Mono，中文回退栈随平台',
    fontSize: '字号',
    decreaseFontSize: '减小字号',
    increaseFontSize: '增大字号',
    ligatures: '连字',
    ligaturesHint: '=> !== 等操作符合并渲染',
    defaultTerminal: '默认终端',
    defaultTerminalHint: 'quick launch 的「终端」芯片按此启动',
    preferences: 'settings · preferences',
    description: '布局与控件沿用定稿原型；各项设置直读写 settingsStore。',
    mapleMono: 'Maple Mono',
    pixels: (value: number) => `${value}px`,
    themeErrors: '用户主题加载失败'
  },
  newSession: {
    title: 'New Session',
    terminal: '终端',
    quickTerminalHint: '按系统默认方式启动',
    chooseTerminal: '选择终端',
    chooseTerminalHint: '点击一项即可启动',
    configureCli: '配置 CLI 会话',
    chooseCli: '选择一个 AI CLI 开始',
    newCli: (name: string) => `新建 ${name}`,
    configureThenLaunch: '配置会话后启动',
    sessionName: '名称',
    sessionNamePlaceholder: '会话名称',
    workspace: '工作区',
    chooseWorkspace: '选择目录',
    arguments: '启动参数',
    runtime: '版本',
    windows: 'Windows',
    windowsHint: '本机 Windows 环境',
    wsl: 'WSL',
    wslHint: '通过 WSL 启动',
    rememberDefault: '下次默认以该方式启动',
    launch: '启动',
    defaultBadge: '默认',
    terminalFallback: '系统默认终端',
    workspacePlaceholder: '请选择工作区',
    argumentsPlaceholder: '--flag value',
    p2Placeholder: 'CLI 与运行环境选项将在 P3 接入'
  },
  shell: {
    homeLabel: 'home · app shell',
    homeTitle: 'Welcome back.',
    homeHint: '首页内容将在 P3 接入；三态导航与终端路由已可用。',
    settingsHint: 'P2 先开放导航模式；完整设置项将在 P3 接入。',
    unavailableTerminal: '这个演示会话没有可打开的终端。'
  },
  mock: {
    sessions: [
      { name: 'Codex', detail: '运行 pnpm test --filter demo' },
      { name: 'Claude Code', detail: '思考中：检索 ipc-contract 引用' },
      { name: 'Codex', detail: '等待批准：写入 src/main.ts' },
      { name: 'Aider', detail: '等待确认：提交 4 个文件的改动' },
      { name: 'Gemini CLI', detail: '完成：生成 release notes' },
      { name: 'Codex', detail: '出错：tests/ipc.test.ts 3 个用例失败' },
      { name: 'OpenCode', detail: '出错：electron-vite build 退出码 1' },
      { name: 'Claude Code', detail: '等待批准：删除旧的迁移脚本' },
      { name: 'Cursor Agent', detail: '等待确认：重构 sidebar 布局' },
      { name: 'Claude Code', detail: '完成：补齐 tabs e2e 断言' },
      { name: 'Gemini CLI', detail: '出错：API rate limit exceeded' },
      { name: 'Codex', detail: '等待批准：更新 package.json 依赖' },
      { name: 'Aider', detail: '空闲：等待下一个 prompt' },
      { name: 'OpenCode', detail: '等待确认：迁移到 Tailwind v4' },
      { name: 'Claude Code', detail: '出错：eslint 12 个问题未修复' },
      { name: 'Warp Agent', detail: '已退出：exit code 0' },
      { name: 'Continue', detail: '出错：无法连接本地模型服务' }
    ],
    history: [
      { title: 'tool_call · Write', detail: 'src/App.tsx · 写入 48 行' },
      { title: 'tool_call · Bash', detail: 'pnpm test --filter demo' },
      { title: '已批准', detail: '提交 4 个文件的改动' },
      { title: 'tool_call · Read', detail: 'src/components/TrueFocus.jsx' },
      { title: '会话完成', detail: '生成 release notes · 成功' },
      { title: 'tool_call · Edit', detail: 'vite.config.ts · patch' },
      { title: 'assistant', detail: '已完成 sidebar 布局重构，请 review' },
      { title: 'tool_call · Glob', detail: '**/*.{ts,tsx} · 126 files' }
    ]
  }
} as const
